ALTER TABLE [dbo].[Score]
    ADD CONSTRAINT [PK_Score] PRIMARY KEY CLUSTERED ([PlayerId] ASC, [GameId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

