<?xml version="1.0" encoding="utf-8"?><Database Name="TC2" Class="TC2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=TC2;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TC2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Card" Member="Cards">
    <Type Name="Card">
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CardAlias" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Card_UserTableInventory" Member="UserTableInventories" ThisKey="CardId" OtherKey="CardId" Type="UserTableInventory" />
      <Association Name="Card_TableState" Member="TableStates" ThisKey="CardId" OtherKey="CardId" Type="TableState" />
      <Association Name="Card_TableUserCard" Member="TableUserCards" ThisKey="CardId" OtherKey="CardId" Type="TableUserCard" />
      <Association Name="Card_TableHistory" Member="TableHistories" ThisKey="CardId" OtherKey="CardId" Type="TableHistory" />
    </Type>
  </Table>
  <Table Name="dbo.UserTableInventory" Member="UserTableInventories">
    <Type Name="UserTableInventory">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Card_UserTableInventory" Member="Card" ThisKey="CardId" OtherKey="CardId" Type="Card" IsForeignKey="true" />
      <Association Name="User_UserTableInventory" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_UserTableInventory" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameResult" Member="GameResults">
    <Type Name="GameResult">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WinnerUserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_GameResult" Member="User" ThisKey="WinnerUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_GameResult" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameScore" Member="GameScores">
    <Type Name="GameScore">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_GameScore" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_GameScore" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TableState" Member="TableStates">
    <Type Name="TableState">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Card_TableState" Member="Card" ThisKey="CardId" OtherKey="CardId" Type="Card" IsForeignKey="true" />
      <Association Name="User_TableState" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_TableState" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Token" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TokenLastHit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_UserTableInventory" Member="UserTableInventories" ThisKey="UserId" OtherKey="UserId" Type="UserTableInventory" />
      <Association Name="User_GameResult" Member="GameResults" ThisKey="UserId" OtherKey="WinnerUserId" Type="GameResult" />
      <Association Name="User_GameScore" Member="GameScores" ThisKey="UserId" OtherKey="UserId" Type="GameScore" />
      <Association Name="User_TableState" Member="TableStates" ThisKey="UserId" OtherKey="UserId" Type="TableState" />
      <Association Name="User_TableUser" Member="TableUsers" ThisKey="UserId" OtherKey="UserId" Type="TableUser" />
      <Association Name="User_TableHistory" Member="TableHistories" ThisKey="UserId" OtherKey="UserId" Type="TableHistory" />
      <Association Name="User_Table" Member="Tables" ThisKey="UserId" OtherKey="LastWinnerUserId" Type="Table" />
      <Association Name="User_Table1" Member="Tables1" ThisKey="UserId" OtherKey="OwnerUserId" Type="Table" />
    </Type>
  </Table>
  <Table Name="dbo.TableUserCard" Member="TableUserCards">
    <Type Name="TableUserCard">
      <Column Name="TableUserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Card_TableUserCard" Member="Card" ThisKey="CardId" OtherKey="CardId" Type="Card" IsForeignKey="true" />
      <Association Name="TableUser_TableUserCard" Member="TableUser" ThisKey="TableUserId" OtherKey="TableUserId" Type="TableUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TableUser" Member="TableUsers">
    <Type Name="TableUser">
      <Column Name="TableUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDominant" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsTurnPlayer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TableUser_TableUserCard" Member="TableUserCards" ThisKey="TableUserId" OtherKey="TableUserId" Type="TableUserCard" />
      <Association Name="User_TableUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_TableUser" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TableHistory" Member="TableHistories">
    <Type Name="TableHistory">
      <Column Name="TableHistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Card_TableHistory" Member="Card" ThisKey="CardId" OtherKey="CardId" Type="Card" IsForeignKey="true" />
      <Association Name="User_TableHistory" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Table_TableHistory" Member="Table" ThisKey="TableId" OtherKey="TableId" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Suspended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CurrentSuit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Trump" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GameStarted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HandsAccumulated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TurnStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastWinnerUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastWinnerTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrumpChooser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Table_UserTableInventory" Member="UserTableInventories" ThisKey="TableId" OtherKey="TableId" Type="UserTableInventory" />
      <Association Name="Table_GameResult" Member="GameResults" ThisKey="TableId" OtherKey="TableId" Type="GameResult" />
      <Association Name="Table_GameScore" Member="GameScores" ThisKey="TableId" OtherKey="TableId" Type="GameScore" />
      <Association Name="Table_TableState" Member="TableStates" ThisKey="TableId" OtherKey="TableId" Type="TableState" />
      <Association Name="Table_TableUser" Member="TableUsers" ThisKey="TableId" OtherKey="TableId" Type="TableUser" />
      <Association Name="Table_TableHistory" Member="TableHistories" ThisKey="TableId" OtherKey="TableId" Type="TableHistory" />
      <Association Name="User_Table" Member="User" ThisKey="LastWinnerUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_Table1" Member="User1" ThisKey="OwnerUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.usp_RegisterUser" Method="RegisterUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_RegisterUserResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ChangePassword" Method="ChangePassword">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CurrentPassword" Parameter="currentPassword" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NewPassword" Parameter="newPassword" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="usp_ChangePasswordResult">
      <Column Name="LoginToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ErrorCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ListJoinableTables" Method="ListJoinableTables">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="usp_ListJoinableTablesResult">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SlotsAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ListUserTables" Method="ListUserTables">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="usp_ListUserTablesResult">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SlotsAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_CreateTable" Method="CreateTable">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="TableName" Parameter="tableName" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="usp_CreateTableResult">
      <Column Name="TableId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AvailableSlots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_SuspendTable" Method="SuspendTable">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="TableId" Parameter="tableId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_JoinTable" Method="JoinTable">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="TableId" Parameter="tableId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetTableTimestamp" Method="GetTableTimestamp">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="TableId" Parameter="tableId" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_GetTableTimestampResult">
      <Column Name="Timestamp" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_LogIn" Method="LogIn">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="usp_LogInResult">
      <Column Name="LoginToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ErrorCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ListTablesUserIsOn" Method="ListTablesUserIsOn">
    <Parameter Name="LoginToken" Parameter="loginToken" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="usp_ListTablesUserIsOnResult">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SlotsAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>